{"name": "test_mul[failed]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 242 == 333", "trace": "self = <pytest_practice.testcases.test_calc.TestCalcutor object at 0x03DC3B20>\nget_calc = <pytest_practice.common.calc.Calculator object at 0x03E64880>\nget_mul_datas = [11, 22, 333]\n\n    @allure.story(\"测试乘法\")\n    def test_mul(self, get_calc, get_mul_datas):\n        # 步骤说明\n        with allure.step(\"计算两个数的乘积\"):\n            result = get_calc.mul(get_mul_datas[0], get_mul_datas[1])\n        if isinstance(result, float):\n            result = round(result, 2)\n>       assert result == get_mul_datas[2]\nE       assert 242 == 333\n\ntestcases\\test_calc.py:47: AssertionError"}, "steps": [{"name": "计算两个数的乘积", "status": "passed", "start": 1612096144687, "stop": 1612096144687}], "parameters": [{"name": "get_mul_datas", "value": "[11, 22, 333]"}], "start": 1612096144686, "stop": 1612096144687, "uuid": "507f65b6-d3d8-4a76-b1b7-e5543e1565bb", "historyId": "ab74f40bad377ee3a83ea79e1e0b8f50", "testCaseId": "0b07cb69a0f7cc575c82e397a0f8f548", "fullName": "testcases.test_calc.TestCalcutor#test_mul", "labels": [{"name": "story", "value": "测试乘法"}, {"name": "feature", "value": "计算器测试"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_calc"}, {"name": "subSuite", "value": "TestCalcutor"}, {"name": "host", "value": "XTZ-01705042203"}, {"name": "thread", "value": "12664-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_calc"}]}